### PR TITLE
feat: change path comparison

### PR DESCRIPTION
**Pull request by carloschneider**
Solution proposal for #78

Some examples how to use:

- http://request2.com/:path\\?page=([^&]*)&ok=([^&]*)
- http://request2.com/search(.*)

BREAKING CHANGE: after this change you'll need to escape the question mark (?) to ensure it does not flag the parameter as optional.

Read more here: https://github.com/pillarjs/path-to-regexp#optional

### CODE REVIEW

**Comment by nutboltu** [comment]
@carloschneider  this will be a breaking change. I would suggest to keep the existing behaviour and add a new variable to disable param check

**Comment by carloschneider** [comment]
@nutboltu Seriously? It was what I proposal last year and you suggested to do what I did right now. Well, my PRs and others are here for you or any other use it in the future to create a solution that will please you.

Anyway, I've forked the repo and solve my problem.

**Comment by JoaoBrlt** [comment]
@nutboltu @carloschneider I've just implemented that on #191 :wink:

**Comment by nutboltu** [comment]
@carloschneider, we are still in the same proposal, but to keep the older versions up and running, we need a flag variable to enable this. Please see the PR #191  raised by @JoaoBrlt . Let me know if I missed anything

**Pull request closed without merging**
